package demo;

import java.awt.Color;
import raven.chart.geo.utils.GeoData;

/**
 *
 * @author RAVEN
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        setOpaque(false);
        geoChart.load(GeoData.Resolution.LOW);
        geoChart.getGeoChart().zoom(2);
        geoChart.putData("Vietnam", 8691, new Color(167, 85, 201));
        geoChart.putData("India", 7770, new Color(85, 159, 201));
        geoChart.putData("Philippines", 7017, new Color(89, 152, 97));
        geoChart.putData("Indonesia", 2869, new Color(200, 149, 61));
        geoChart.putData("Morocco", 2409, new Color(73, 104, 210));
        geoChart.putData("Mexico", 2023, new Color(180, 73, 168));
        geoChart.putData("Brazil", 1988, new Color(82, 209, 211));
        geoChart.setGeoChartDataView(geoChartDataView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new demo.PanelShadow();
        geoChart = new raven.chart.geo.GeoChart();
        geoChartDataView = new raven.chart.geo.GeoChartDataView();

        panelShadow1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        geoChart.setBackground(new java.awt.Color(255, 255, 255));
        geoChart.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geoChart, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(geoChartDataView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geoChart, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geoChartDataView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.chart.geo.GeoChart geoChart;
    private raven.chart.geo.GeoChartDataView geoChartDataView;
    private demo.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
